image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
tasks:
- package: |
    cd raiguard.me
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d raiguard.srht.site site.tar.gz
