image: archlinux
oauth: pages.sr.ht/PAGES:RW
packages:
- dart-sass
- hut
environment:
  site: raiguard.me
tasks:
- generate: |
    cd $site
    ./build.sh
- package: |
    cd $site/build
    tar -cvz . > ../../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
